/*
 * main.h
 *
 *  Created on: Nov 25, 2023
 *      Author: incano
 */

#ifndef MAIN_H_
#define MAIN_H_

#include "stm32f1xx.h"
#include "stdbool.h"
#include "string.h"
#include "stdio.h"


#define	RX_BUFF_SIZE	256
#define TX_BUFF_SIZE	256
#define DELAY_VAL		1000000


#define reset()		GPIOC->ODR = ~(GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6|GPIO_ODR_ODR7);

#define disp_0()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR5);
#define disp_1()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR5);
#define disp_2()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR6);
#define disp_3()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_4()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR2|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_5()	GPIOC->ODR |= (GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_6()	GPIOC->ODR |= (GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_7()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR5);
#define disp_8()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_9()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_10()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_11()	GPIOC->ODR |= (GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_12()	GPIOC->ODR |= (GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR4);
#define disp_13()	GPIOC->ODR |= (GPIO_ODR_ODR0|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR5|GPIO_ODR_ODR6);
#define disp_14()	GPIOC->ODR |= (GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR4|GPIO_ODR_ODR6);
#define disp_15()	GPIOC->ODR |= (GPIO_ODR_ODR1|GPIO_ODR_ODR2|GPIO_ODR_ODR3|GPIO_ODR_ODR6);

void initClk(void);
void init_portC(void);
void initButton(void);
void initTIM2(void);
void display(int i);
void delay(uint32_t value);






void initUSART2(void);
void txStr(char *str, bool crlf);
void ExecuteCommand(void);


#endif /* MAIN_H_ */
